title: About
layout:
  -
    width: 2/3
    sections:
      -
        type: fields
        fields:
          -
            label: Intro
            name: intro
            type: textarea
            validate:
              max: 10
              min: 5
          -
            label: Text
            name: text
            type: textarea
            required: true
  -
    width: 1/3
    sections:
      -
        headline: Images
        type: files
